kind: pipeline
name: android-build
type: docker

steps:
  - name: build-android
    image: docker.sotech.xyz/xamarin/android:30-latest
    environment:
      KEYPASS:
        from_secret: KEYPASS
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - export ANDROID_HOME=/usr/lib/android-sdk
      - export ANDROID_SDK_ROOT=/usr/lib/android-sdk
      - mkdir /root && mkdir /root/Library && mkdir /root/Library/Android
      - ln -s /usr/lib/android-sdk /root/Library/Android/sdk
      - msbuild /p:Configuration="Release" -t:restore AppColeta.Android/SOColeta.Android.csproj
      - msbuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=SOTech /p:AndroidSigningKeyPass=$KEYPASS /p:OutputPath="../../publish_android/" "/p:AndroidSigningKeyStore=/tmp/sotech.keystore" /p:AndroidSigningStorePass=$KEYPASS AppColeta.Android/SOColeta.Android.csproj