kind: pipeline
name: android-build
type: docker

steps:
  - name: build-android
    image: tafilz/xamarin-android:29
    environment:
      KEYPASS:
        from_secret: KEYPASS
      KEYFILE:
        from_secret: CERT_FILE
      PRIVFILE:
        from_secret: PRIV_KEY_FILE
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - ls
      - cat /etc/*release
      - echo $KEYFILE > certificate.pem
      - echo $PRIVFILE > key.pem
      - update-ca-certificates
      - msbuild /p:Configuration="Release" -t:restore AppColeta.Android/SOColeta.Android.csproj
      - msbuild /t:SignAndroidPackage /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=SOTech /p:AndroidSigningKeyPass=$KEYPASS /p:OutputPath="../../publish_android/" "/p:AndroidSigningKeyStore=SOTech.keystore" "/p:AndroidSigningStorePass=$KEYPASS AppColeta.Android/SOColeta.Android.csproj