kind: pipeline
name: android-build
type: docker

steps:
  - name: build-android
    image: tafilz/xamarin-android:29
    failure: ignore
    environment:
      KEYPASS:
        from_secret: KEYPASS
      KEYFILE:
        from_secret: CERT_FILE
      PRIVFILE:
        from_secret: PRIV_KEY_FILE
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - echo $KEYFILE > certificate.pem
      - echo $PRIVFILE > key.pem
      - dos2unix key.pem
      - openssl pkcs12 -export -out cert.p12 -in certificate.pem -inkey key.pem -passin pass:$KEYPASS -passout pass:$KEYPASS
      - keytool -importkeystore -srckeystore cert.p12 -srcstoretype PKCS12 -destkeystore sotech.keystore -deststoretype JKS -srcstorepass $KEYPASS -deststorepass $KEYPASS -srcalias SOTech -destalias SOTech -srckeypass $KEYPASS -destkeypass $KEYPASS -noprompt
      - msbuild AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /restore
      - msbuild /t:SignAndroidPackage /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=SOTech /p:AndroidSigningKeyPass=$KEYPASS /p:OutputPath="../../publish_android/" "/p:AndroidSigningKeyStore=sotech.keystore" "/p:AndroidSigningStorePass=$KEYPASS AppColeta.Android/AppColeta.Android.csproj