kind: pipeline
name: android-build
type: docker

steps:
  - name: build-android
    image: docker.sotech.xyz/xamarin/android:29-latest
    environment:
      KEYPASS:
        from_secret: KEYPASS
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - msbuild /p:Configuration="Release" -t:restore AppColeta.Android/SOColeta.Android.csproj
      - msbuild /t:SignAndroidPackage /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=SOTech /p:AndroidSigningKeyPass=$KEYPASS /p:OutputPath="../../publish_android/" "/p:AndroidSigningKeyStore=/tmp/sotech.keystore" "/p:AndroidSigningStorePass=$KEYPASS AppColeta.Android/SOColeta.Android.csproj