kind: pipeline
name: android-build
type: docker

steps:
  - name: say-hello
    image: busybox
    commands:
      - echo hello-world
  - name: build-android-test
    image: tafilz/xamarin-android:29
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /restore
      - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:PackageForAndroid /p:OutputPath="../../publish_android/"
      - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:SignAndroidPackage /p:OutputPath="../../publish_android/"
  - name: build-android
    image: tafilz/xamarin-android:29
    artifacts:
      paths:
        - publish_android/*.apk
      script:
        - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
        - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /restore
        - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:PackageForAndroid /p:OutputPath="../../publish_android/"
        - msbuild src/AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:SignAndroidPackage /p:OutputPath="../../publish_android/"