kind: pipeline
name: android-build
type: docker

steps:
  - name: build-android
    image: tafilz/xamarin-android:29
    environment:
      KEYPASS:
        from_secret: KEYPASS
      KEYFILE:
        from_secret: CERT_FILE
    commands:
      - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
      - ls
      - echo $KEYFILE > cert.pem
      - keytool -destkeystore sotech.keystore -deststoretype jks -deststorepass $KEYPASS -destalias SOTech
      - msbuild AppColeta.Android/AppColeta.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /restore
      - msbuild /t:SignAndroidPackage /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=SOTech /p:AndroidSigningKeyPass=$KEYPASS /p:OutputPath="../../publish_android/" "/p:AndroidSigningKeyStore=sotech.keystore" "/p:AndroidSigningStorePass=$KEYPASS AppColeta.Android/AppColeta.Android.csproj